@baseUrl = http://localhost:3000
@authToken = Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Ijk1MTg5MTkxMTA3NjA1NDM0NGUxNWUyNTY0MjViYjQyNWVlYjNhNWMiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiU2FzaCBWw6F6cXVleiIsImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9wcm80ZGIiLCJhdWQiOiJwcm80ZGIiLCJhdXRoX3RpbWUiOjE3NjQ3NzE1NDYsInVzZXJfaWQiOiIwWWNybHJHREFqT09IZGx3QXBoRzlxSnpsUTEyIiwic3ViIjoiMFljcmxyR0RBak9PSGRsd0FwaEc5cUp6bFExMiIsImlhdCI6MTc2NDc3MTU0NiwiZXhwIjoxNzY0Nzc1MTQ2LCJlbWFpbCI6ImFsdmFyby52YXpxdWV6LjE3MTZAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImFsdmFyby52YXpxdWV6LjE3MTZAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.JCo4fq139R90pC--REtU5k6oS4NbhN604oO6W-NkTjIkfhNJ67VFcAXx9ndrdKx5s1f4ZbQzEohw8EHFQ03BP3LkLUwZCH2E11ovPh1pnfTzZUre05DDQmPnsw-T-d7yT9lxKIiqIDaA5_qs0bAHHFN5jkiu_RpQ4k5fIExmrK4YN7zT8A4Dw_iwJFZRq2PpqfmEYKur-QgcnNZwU_eEOyZUFYONaxJUBiZcWs63P4Dom3Wp3-awa7zMEMH3FUhfbllrQysdD1ZpN2iJs8eMR8fi8LC2TF6pqR452Esyb9_ZRr9HtvCILBiysShHGiojE1cwW84wWuXsPo041KIcmw
@sessionId = ab170a12-8696-4e6a-96c4-6d453ec242e6

### Health Check
GET {{baseUrl}}/health

### (SESSIONS) Crear nueva sesión (Transcribir ES)
# NECESITA TOKEN
# Esta respuesta te dará un "sessionId". la variable @sessionId
POST {{baseUrl}}/api/sessions
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary
Authorization: {{authToken}}

------WebKitFormBoundary
Content-Disposition: form-data; name="language"

es
------WebKitFormBoundary
Content-Disposition: form-data; name="audio"; filename="sampleES.m4a"
Content-Type: audio/mp4

< ./temp/sampleES.m4a
------WebKitFormBoundary--

###
### (SESSIONS) Crear nueva sesión (Transcribir EN)
# NECESITA TOKEN
POST {{baseUrl}}/api/sessions
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary
Authorization: {{authToken}}

------WebKitFormBoundary
Content-Disposition: form-data; name="language"

en
------WebKitFormBoundary
Content-Disposition: form-data; name="audio"; filename="sampleEN.m4a"
Content-Type: audio/mp4

< ./temp/sampleEN.m4a
------WebKitFormBoundary--

###
### (SESSIONS) Listar todas las sesiones del usuario
# NECESITA TOKEN
GET {{baseUrl}}/api/sessions?limit=5
Authorization: {{authToken}}

###
### (SESSIONS) Obtener detalles de una sesión específica
# NECESITA TOKEN (y @sessionId)
GET {{baseUrl}}/api/sessions/{{sessionId}}
Authorization: {{authToken}}

###
### (SESSIONS) Obtener audio (Debe fallar con 501)
# Esta ruta está deshabilitada (porque no usamos Storage)
# Debería devolver un error 501 "Not Implemented".
GET {{baseUrl}}/api/sessions/{{sessionId}}/audio
Authorization: {{authToken}}

###
### (SESSIONS) Borrar una sesión
# NECESITA TOKEN (y @sessionId)
DELETE {{baseUrl}}/api/sessions/{{sessionId}}
Authorization: {{authToken}}