@baseUrl = http://localhost:3000/api
@token = eyJhbGciOiJSUzI1NiIsImtpZCI6IjcwZmM5YzU0YjhiMjQyMWZmMTgyOTgxNTQyZmQ0NjRlOWJlYzM1NDUiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiQWx1bW5vIGRlIFBydWViYSIsImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9wcm80ZGIiLCJhdWQiOiJwcm80ZGIiLCJhdXRoX3RpbWUiOjE3NzU5NDUzNDcsInVzZXJfaWQiOiIzMmJ6ZDR1dHdQY1NuZVpMNVBRUFJzMU90WGwxIiwic3ViIjoiMzJiemQ0dXR3UGNTbmVaTDVQUVBSczFPdFhsMSIsImlhdCI6MTc3NTk0NTM0NywiZXhwIjoxNzc1OTQ4OTQ3LCJlbWFpbCI6ImFsdW1ubzFAdnItaW50ZXJ2aWV3LmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJhbHVtbm8xQHZyLWludGVydmlldy5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.AuSlHjRPd_5KgAx0EUSbEk51b9gKXrUqVxiQw3pfDtVOHl_4PNjfLluCSLIZuXMva7xuZBMxY-0aRGdIA21a-k1a06QuF1AnRXSGzqHSfjYqn8SThvJHatUR5gSVnAbDuOwzCu8wFv2oaerhftMSaB_scIpnllklsXHWbCyAVvHgEhsRk1K1XDpyA3r-O5OUBHoreo1i5Z7NSYWT6PWJtCwE-Skp0tyLLsUlOiQ_TLL058kp6iOEGsnXSImKuMFh_o_pgvNG-UMGv9YvkA1_LxSg1wweasgv8mMavrTJSzo7L7FxtfwUOzKUUEUm06oWxVXzz4D2kvmw18UJYbNirw

### register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "email": "alumno1@vr-interview.com",
    "password": "password123",
    "name": "Alumno de Prueba"
}

### login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "alumno1@vr-interview.com",
    "password": "password123"
}


###
GET {{baseUrl}}/auth/profile
Authorization: Bearer {{token}}

### 
POST {{baseUrl}}/sessions
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----MyAwesomeBoundary

------MyAwesomeBoundary
Content-Disposition: form-data; name="language"

es
------MyAwesomeBoundary
Content-Disposition: form-data; name="conversationHistory"

[{"role":"recruiter", "text": "Hola, bienvenido a la entrevista. ¿Estás listo?"}]
------MyAwesomeBoundary
Content-Disposition: form-data; name="audio"; filename="Convai_Conversation_20260407_233542.wav"
Content-Type: audio/wav

< ./Convai_Conversation_20260407_233542.wav
------MyAwesomeBoundary--


### 2B. Listar el historial de sesiones (Para las gráficas de progreso)
GET {{baseUrl}}/sessions?limit=5
Authorization: Bearer {{token}}


### 2C. Obtener los detalles completos de UNA sesión
# 🎯 REEMPLAZA EL sessionId CON EL ID QUE OBTUVISTE EN EL PASO 2A O 2B
@sessionId = tu-session-id-aqui

GET {{baseUrl}}/sessions/{{sessionId}}
Authorization: Bearer {{token}}


### 2D. Eliminar una sesión
DELETE {{baseUrl}}/sessions/{{sessionId}}
Authorization: Bearer {{token}}